package app_func

import (
	"go-kafka-clean-architecture/app_func/registry"
)

func StartEventContextHttpContextRestApiSqlGormMySqlEventApiBrasil() {
	registry.EventContextHttpContextRestApiSqlGormMySqlEventApiBrasil()
}

func StartEventContextHttpContextRestApiSqlGormPostgresEventApiBrasil() {
	registry.EventContextHttpContextRestApiSqlGormPostgresEventApiBrasil()
}

func StartEventContextHttpContextRestApiSqlGormMySqlEventApiChile() {
	registry.EventContextHttpContextRestApiSqlGormMySqlEventApiChile()
}

func StartEventContextHttpContextRestApiSqlGormPostgresEventApiChile() {
	registry.EventContextHttpContextRestApiSqlGormPostgresEventApiChile()
}

func StartEventContextHttpContextRestApiSqlHandlerMySqlEventApiBrasil() {
	registry.EventContextHttpContextRestApiSqlHandlerMySqlEventApiBrasil()
}

func StartEventContextHttpContextRestApiSqlHandlerPostgresEventApiBrasil() {
	registry.EventContextHttpContextRestApiSqlHandlerPostgresEventApiBrasil()
}

func StartEventContextHttpContextRestApiSqlHandlerMySqlEventApiChile() {
	registry.EventContextHttpContextRestApiSqlHandlerMySqlEventApiChile()
}

func StartEventContextHttpContextRestApiSqlHandlerPostgresEventApiChile() {
	registry.EventContextHttpContextRestApiSqlHandlerPostgresEventApiChile()
}

func StartEventContextJsonContextRestApiSqlGormMySqlEventApiBrasil() {
	registry.EventContextJsonContextRestApiSqlGormMySqlEventApiBrasil()
}

func StartEventContextJsonContextRestApiSqlGormPostgresEventApiBrasil() {
	registry.EventContextJsonContextRestApiSqlGormPostgresEventApiBrasil()
}

func StartEventContextJsonContextRestApiSqlGormMySqlEventApiChile() {
	registry.EventContextJsonContextRestApiSqlGormMySqlEventApiChile()
}

func StartEventContextJsonContextRestApiSqlGormPostgresEventApiChile() {
	registry.EventContextJsonContextRestApiSqlGormPostgresEventApiChile()
}

func StartEventContextJsonContextRestApiSqlHandlerMySqlEventApiBrasil() {
	registry.EventContextJsonContextRestApiSqlHandlerMySqlEventApiBrasil()
}

func StartEventContextJsonContextRestApiSqlHandlerPostgresEventApiBrasil() {
	registry.EventContextJsonContextRestApiSqlHandlerPostgresEventApiBrasil()
}

func StartEventContextJsonContextRestApiSqlHandlerMySqlEventApiChile() {
	registry.EventContextJsonContextRestApiSqlHandlerMySqlEventApiChile()
}

func StartEventContextJsonContextRestApiSqlHandlerPostgresEventApiChile() {
	registry.EventContextJsonContextRestApiSqlHandlerPostgresEventApiChile()
}
