version: '3'
services:
  mysql:
    image: mysql
    container_name: clean-architecture-database-mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSql_DATABASE: cleanarchitecture
      MYSql_USER: cleanarchitecture
      MYSql_PASSWORD: cleanarchitecture
      MYSql_ROOT_PASSWORD: example
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-schema.sql:/docker-entrypoint-initdb.d/mysql-schema.sql
  postgres:
    image: postgres
    container_name: clean-architecture-database-postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cleanarchitecture
      POSTGRES_USER: cleanarchitecture
      POSTGRES_PASSWORD: cleanarchitecture
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/postgres-schema.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    depends_on:
      - mysql
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  broker:
    image: confluentinc/cp-server
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_CREATE_TOPICS: "product:1:1"

